# redis相关
redis_host: localhost
redis_port: 6379
redis_password: password

# zookeeper地址,host:port, 多个用,隔开
zk_addr: localhost:2181,localhost:2182,localhost:2183

# mysql
mysql_host: localhost
mysql_port: 3306
mysql_db: better-together
mysql_username: username
mysql_password: password

# rocket name-server地址
rocketmq_name_server: localhost:9876

# xxl-job
xxl_admin_addresses: http://localhost:8805
xxl_admin_access_token: token

## qq邮箱服务
mail_server_username: username
mail_server_password: password

## oss
oss_endpoint: wait_fill
oss_accessKeyId: wait_fill
oss_accessKeySecret: wait_fill
oss_secret: false
oss_stsEndpoint: wait_fill
oss_roleArn: wait_fill

# jwt
jwt_secret: wait_fill

# 动态RSA
rsa_primaryKey: wait_fill
rsa_publicKey: wait_fill

## druid
druid_stat_enable: false
druid_state_username: wait_fill
druid_state_password: wait_fill

spring:
  datasource:
    initialization-mode: ALWAYS
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver  # 优化sql显示插件，对性能有一定影响
      url: jdbc:p6spy:mysql://${mysql_host}:${mysql_port}/${mysql_db}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&tinyInt1isBit=false
      username: ${mysql_username}
      password: ${mysql_password} # https://github.com/alibaba/druid/wiki/%E4%BD%BF%E7%94%A8ConfigFilter可以配置生数据库加密
      initial-size: 5
      asyncInit: true
      max-active: 30
      min-idle: 10
      keep-alive: true
      max-wait: 60000
      use-unfair-lock: true
      # 回收连接相关
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 600000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      poolPreparedStatements: false
      max-open-prepared-statements: 20
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 3000
        wall:
          enabled: true # 开启WallFilter
          db-type: mysql
      ## 开启内置监控界面 访问路径: /context-path/druid/index.html
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
        allow:

  # 国际化资源文件
  messages:
    basename: exception/exception
    use-code-as-default-message: false

  redis:
    redis:
      # 使用redisson作为redis的客户端，其实redisson是可以优先使用RedisProperties作为配置文件的，这里为了准确说明含义，去掉了RedisProperties的配置方式
      redisson:
        # org.redisson.config.Config
        file: classpath:redisson-single.yaml

  mail:
    username: ${mail_server_username}                # 用来验证授权的邮件用户名
    password: ${mail_server_password}                # 根据QQ邮箱设置-账户里生成的第三方登陆授权码，可用来代替密码登陆
    host: smtp.qq.com                         # 邮件服务器类型
    properties.mail.smtp.ssl.enable: true # 用以支持授权码登陆

rocketmq:
  name-server: ${rocketmq_name_server}
  producer:
    group: better-together-producer-group
    send-message-timeout: 10000
    retryNextServer: true

distributed:
  lock:
    zookeeper:
      root: /distributed_lock
      connectString: ${zk_addr}

xxl-job:
  adminAddresses: ${xxl_admin_addresses}
  accessToken: ${xxl_admin_access_token} # 访问token, 需要和xxl-job-admin里的配置一致
  appName: auto # 以spring.application.name
  logPath: /opt/services/xxl-job/logs/jobhandler # 日志目录
  logRetentionDays: 7 # 日志保留天数

customs: # 自定义的属性最好都写在custom前缀下，方便辨认
  global-properties:
    snowflakeWorkerId: 1      # worker Id can't be greater than 31 or less than 0
    snowflakeDataCenterId: 1  # dataCenterId Id can't be greater than 31 or less than 0
    ignoreErrorTraceProfile: # 过滤将异常堆栈信息输出打前端接口返回值的环境
      - pre
      - prod
    exception200: true  # 异常模式， true标识使用异常时保证http状态码为200，使用返回数据标识具体异常
  authentication:
    reset-password: 123456
    white-login-name-list:
      - 1041765757@qq.com
      - 123@test.com

  ext:
    ## oss服务配置 com.ddf.boot.common.ext.oss.config.OssProperties
    oss:
      endpoint: ${oss_endpoint}
      accessKeyId: ${oss_accessKeyId}
      accessKeySecret: ${oss_accessKeySecret}
      secret: ${oss_secret}
      stsEndpoint: ${oss_stsEndpoint}
      roleArn: ${oss_roleArn}
      roleSessionName: ${spring.application.name}
      durationSeconds: 1800
      buckets:
        - bucketName: ddf-private
          bucketEndpoint: ddf-private.oss-cn-shanghai.aliyuncs.com
          primary: true
    ## 短信服务配置 com.ddf.boot.common.ext.sms.config.SmsProperties
    sms:
      endpoint: dysmsapi.aliyuncs.com
      protocol: HTTP
      secretAccessKey: true
      accessKeyId: ${oss_accessKeyId}
      accessKeySecret: ${oss_accessKeySecret}
      sinaName: ABC商城
      templateCode: SMS_204455240
      useRandomCode: true


  jwt:
    secret: ${jwt_secret}
    expiredMinute: 1080  # jwt token过期时间，单位分钟
    refreshTokenMinute: 10  # 在jwt token有效时间剩余达到了这个时间（分钟），如果用户在线（即调用了任意接口）则服务端主动刷新用户token并返回，需要前端配合处理重新替换用户token
    ignores: ## 接口用户认证请求拦截忽略路径
      - path: /v2/**
      - path: /swagger-ui.html
      - path: /swagger-ui.html/**
      - path: /swagger-resources/**
      - path: /swagger/**
      - path: /webjars/**
      - path: /druid/**
      - path: /csrf
      - path: /app.js
      - path: /websocket.html
      - path: /js/**
      - path: /ws/**
      - path: /pay-ws/**
      - path: /heartCheck.txt
      - path: /index.html
      - path: /favicon.ico
      - path: /sysUser/generateCaptcha
      - path: /sysUser/loginByPassword
  rsa:
    primaryKey: ${rsa_primaryKey}
    publicKey: ${rsa_publicKey}

leaf:
  name: com.sankuai.leaf.opensource.snowflake
  segment:
    enable: false
  snowflake:
    enable: true
    address: ${zk_addr}
