nacos:
  config:
    server-addr: ${nocos_server}
    username: ${nacos_username}
    password: ${nacos_password}
    auto-refresh: true
    config-retry-time: 3000
    namespace: common
    group: DEFAULT_GROUP
    enable-remote-sync-config: false
    type: yaml
    data-ids: common-server,common-mybatis-plus,common-datasource,common-redis,common-mail,common-rabbitmq,common-rocketmq,common-mongo,common-es,common-elasticjob,common-xxl-job,common-jwt,common-global-properties,common-ext-oss,common-ext-sms,common-websocket,common-distributed-lock,common-ids
    ext-config:
      - namespace: spring-boot-quick
        dataId: property-source
        group: dev
        type: properties
        auto-refresh: true

      - dataId: config-properties
        type: properties
        auto-refresh: true

      - dataId: config-server
        type: yaml
        auto-refresh: true



spring:
  datasource:
    initialization-mode: ALWAYS
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver  # 优化sql显示插件，对性能有一定影响
      url: jdbc:p6spy:mysql://${mysql_host}:${mysql_port}/${mysql_db}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&tinyInt1isBit=false
      username: ${mysql_username}
      password: ${mysql_password} # https://github.com/alibaba/druid/wiki/%E4%BD%BF%E7%94%A8ConfigFilter可以配置生数据库加密
      initial-size: 5
      asyncInit: true
      max-active: 30
      min-idle: 10
      keep-alive: true
      max-wait: 60000
      use-unfair-lock: true
      # 回收连接相关
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 600000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      poolPreparedStatements: false
      max-open-prepared-statements: 20
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 3000
        wall:
          enabled: true # 开启WallFilter
          db-type: mysql
      ## 开启内置监控界面 访问路径: /context-path/druid/index.html
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
        allow:

  # 国际化资源文件
  messages:
    basename: exception/exception
    use-code-as-default-message: false

  redis:
    database: 1
    timeout: 1000ms
    host: ${redis_host}
    port: ${redis_port}
    password: ${redis_password}
    redisson:
      # com.ddf.boot.common.redis.config.RedisCustomizeAutoConfiguration
      codec: org.redisson.codec.JsonJacksonCodec

  mail:
    username: ${mail_server_username}                # 用来验证授权的邮件用户名
    password: ${mail_server_password}                # 根据QQ邮箱设置-账户里生成的第三方登陆授权码，可用来代替密码登陆
    host: smtp.qq.com                         # 邮件服务器类型
    properties.mail.smtp.ssl.enable: true # 用以支持授权码登陆

rocketmq:
  name-server: ${rocketmq_name_server}
  producer:
    group: better-together-producer-group
    send-message-timeout: 10000
    retryNextServer: true

distributed:
  lock:
    zookeeper:
      root: /distributed_lock
      connectString: ${zk_addr}

xxl-job:
  adminAddresses: ${xxl_admin_addresses}
  accessToken: ${xxl_admin_access_token} # 访问token, 需要和xxl-job-admin里的配置一致
  appName: auto # 以spring.application.name
  logPath: /opt/services/xxl-job/logs/jobhandler # 日志目录
  logRetentionDays: 7 # 日志保留天数

customs: # 自定义的属性最好都写在custom前缀下，方便辨认
  global-properties:
    snowflakeWorkerId: 1      # worker Id can't be greater than 31 or less than 0
    snowflakeDataCenterId: 1  # dataCenterId Id can't be greater than 31 or less than 0
    ignoreErrorTraceProfile: # 过滤将异常堆栈信息输出打前端接口返回值的环境
      - pre
      - prod
    exception200: true  # 异常模式， true标识使用异常时保证http状态码为200，使用返回数据标识具体异常
  authentication:
    reset-password: 123456
    white-login-name-list:
      - 1041765757@qq.com
      - 123@test.com

  ext:
    ## oss服务配置 com.ddf.boot.common.ext.oss.config.OssProperties
    oss:
      endpoint: ${oss_endpoint}
      accessKeyId: ${oss_accessKeyId}
      accessKeySecret: ${oss_accessKeySecret}
      secret: ${oss_secret}
      stsEndpoint: ${oss_stsEndpoint}
      roleArn: ${oss_roleArn}
      roleSessionName: ${spring.application.name}
      durationSeconds: 1800
      buckets:
        - bucketName: ddf-private
          bucketEndpoint: ddf-private.oss-cn-shanghai.aliyuncs.com
          primary: true
    ## 短信服务配置 com.ddf.boot.common.ext.sms.config.SmsProperties
    sms:
      endpoint: dysmsapi.aliyuncs.com
      protocol: HTTP
      secretAccessKey: true
      accessKeyId: ${oss_accessKeyId}
      accessKeySecret: ${oss_accessKeySecret}
      sinaName: ABC商城
      templateCode: SMS_204455240
      useRandomCode: true


  jwt:
    secret: ${jwt_secret}
    expiredMinute: 1080  # jwt token过期时间，单位分钟
    refreshTokenMinute: 10  # 在jwt token有效时间剩余达到了这个时间（分钟），如果用户在线（即调用了任意接口）则服务端主动刷新用户token并返回，需要前端配合处理重新替换用户token
    ignores: ## 接口用户认证请求拦截忽略路径
      - path: /v2/**
      - path: /swagger-ui.html
      - path: /swagger-ui.html/**
      - path: /swagger-resources/**
      - path: /swagger/**
      - path: /webjars/**
      - path: /druid/**
      - path: /csrf
      - path: /app.js
      - path: /websocket.html
      - path: /js/**
      - path: /ws/**
      - path: /pay-ws/**
      - path: /heartCheck.txt
      - path: /index.html
      - path: /favicon.ico
      - path: /sysUser/generateCaptcha
      - path: /sysUser/loginByPassword
