# 在spring-boot应用中（注意不是spring-cloud），开启这个可以让spring-boot应用具备在启动前就将外部配置加载到spring环境中的能力， 即可通过外部配置各种数据源了
nacos:
  config:
    bootstrap:
      enable: true

server:
  port: 8089
  tomcat:
    max-connections: 10000
    max-threads: 200
    min-spare-threads: 20
  servlet:
    context-path: /better-together

spring:
  profiles:
    active: dev
  application:
    name: better-together

logging:
  level:
    root: info
    com.ddf.boot.common.log.AccessLogAspect: debug
