# redis相关
redis_host: www.snowball.fans
redis_port: 6379
redis_password: 123456

# zookeeper地址,host:port, 多个用,隔开
zk_addr: www.snowball.fans:2181,www.snowball.fans:2182,www.snowball.fans:2183

# mysql
mysql_host: www.snowball.fans
mysql_port: 3306
mysql_db: better-together
mysql_username: develop
mysql_password: 12345678

# rocket name-server地址
rocketmq_name_server: www.snowball.fans:9876

# xxl-job
xxl_admin_addresses: http://www.snowball.fans:8805

spring:
  datasource:
    initialization-mode: ALWAYS
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver  # 优化sql显示插件，对性能有一定影响
      url: jdbc:p6spy:mysql://${mysql_host}:${mysql_port}/${mysql_db}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&tinyInt1isBit=false
      username: ${mysql_username}
      password: ${mysql_password} # https://github.com/alibaba/druid/wiki/%E4%BD%BF%E7%94%A8ConfigFilter可以配置生数据库加密
      initial-size: 5
      asyncInit: true
      max-active: 30
      min-idle: 10
      keep-alive: true
      max-wait: 60000
      use-unfair-lock: true
      # 回收连接相关
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 600000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      poolPreparedStatements: false
      max-open-prepared-statements: 20
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 3000
        wall:
          enabled: true # 开启WallFilter
          db-type: mysql
      ## 开启内置监控界面 访问路径: /context-path/druid/index.html
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: admin
        login-password: 123456
        allow:

  # 国际化资源文件
  messages:
    basename: exception/exception
    use-code-as-default-message: false

  #  redis:
  #    cluster:
  #      max-redirects: 3
  #      nodes: localhost:6601,localhost:6602,localhost:6603
  #    database: 0
  #    jedis:
  #      pool:
  #        max-active: 100
  #        max-idle: 10
  #        min-idle: 0
  #        max-wait: 800ms
  #    timeout: 1000ms
  redis:
    database: 1
    jedis:
      pool:
        max-active: 100
        max-idle: 10
        min-idle: 0
        max-wait: 800ms
    timeout: 1000ms
    host: ${redis_host}
    port: ${redis_port}
    password: ${redis_password}
    # org.redisson.spring.starter.RedissonProperties
    redisson:
      # org.redisson.config.Config
      config:
        # org.redisson.config.SingleServerConfig
        singleServerConfig:
          address: www.snowball.fans:6379
          # org.redisson.config.BaseConfig
          password: 123456
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          clientName: null
          keepAlive: false
          tcpNoDelay: false
          # org.redisson.config.SingleServerConfig
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          pingConnectionInterval: 0
        threads: 16
        nettyThreads: 32
        codec: org.redisson.codec.FstCodec
        transportMode: "NIO"

  mail:
    username: 1041765757@qq.com                # 用来验证授权的邮件用户名
    password: gotartrfwuytbcji                # 根据QQ邮箱设置-账户里生成的第三方登陆授权码，可用来代替密码登陆
    host: smtp.qq.com                         # 邮件服务器类型
    properties.mail.smtp.ssl.enable: true # 用以支持授权码登陆

rocketmq:
  name-server: ${rocketmq_name_server}
  producer:
    group: better-together-producer-group
    send-message-timeout: 10000
    retryNextServer: true

distributed:
  lock:
    zookeeper:
      root: /distributed_lock
      connectString: ${zk_addr}

xxl-job:
  adminAddresses: ${xxl_admin_addresses}
  accessToken: xxl_develop # 访问token, 需要和xxl-job-admin里的配置一致
  appName: auto # 以spring.application.name
  logPath: /opt/services/xxl-job/logs/jobhandler # 日志目录
  logRetentionDays: 7 # 日志保留天数

customs: # 自定义的属性最好都写在custom前缀下，方便辨认
  global-properties:
    snowflakeWorkerId: 1      # worker Id can't be greater than 31 or less than 0
    snowflakeDataCenterId: 1  # dataCenterId Id can't be greater than 31 or less than 0
    ignoreErrorTraceProfile: # 过滤将异常堆栈信息输出打前端接口返回值的环境
      - pre
      - prod
    exception200: true  # 异常模式， true标识使用异常时保证http状态码为200，使用返回数据标识具体异常
  authentication:
    reset-password: 123456
    white-login-name-list:
      - 1041765757@qq.com
      - 123@test.com

  ext:
    ## oss服务配置 com.ddf.boot.common.ext.oss.config.OssProperties
    oss:
      endpoint: oss-cn-shanghai.aliyuncs.com
      accessKeyId: d86b0b8b1c525ee7c4ab54592902baee0fdbba93e20bff5a1016608b9c41053c
      accessKeySecret: 57a8e5c1c3280f3e72c754f4b5a2e326e663ca94414f7ec13a67c2fafd9886ff
      secret: true
      stsEndpoint: sts.cn-shanghai.aliyuncs.com
      roleArn: acs:ram::1863283291831992:role/ramosssts
      roleSessionName: boot-quick
      durationSeconds: 1800
      buckets:
        - bucketName: ddf-private
          bucketEndpoint: ddf-private.oss-cn-shanghai.aliyuncs.com
          primary: true
    ## 短信服务配置 com.ddf.boot.common.ext.sms.config.SmsProperties
    sms:
      endpoint: dysmsapi.aliyuncs.com
      protocol: HTTP
      secretAccessKey: true
      accessKeyId: d86b0b8b1c525ee7c4ab54592902baee0fdbba93e20bff5a1016608b9c41053c
      accessKeySecret: 57a8e5c1c3280f3e72c754f4b5a2e326e663ca94414f7ec13a67c2fafd9886ff
      sinaName: ABC商城
      templateCode: SMS_204455240
      useRandomCode: true


  jwt:
    secret: WoshiyigefenshuajiangfenshuabenlingqiangwoyaobanaxinfangzishuadegengpiaoliangshualefangziyoushuangqiangaiyawodexiaobizibianyabianleYang
    expiredMinute: 1080  # jwt token过期时间，单位分钟
    refreshTokenMinute: 10  # 在jwt token有效时间剩余达到了这个时间（分钟），如果用户在线（即调用了任意接口）则服务端主动刷新用户token并返回，需要前端配合处理重新替换用户token
    ignores: ## 接口用户认证请求拦截忽略路径
      - path: /v2/**
      - path: /swagger-ui.html
      - path: /swagger-ui.html/**
      - path: /swagger-resources/**
      - path: /swagger/**
      - path: /webjars/**
      - path: /druid/**
      - path: /csrf
      - path: /app.js
      - path: /websocket.html
      - path: /js/**
      - path: /ws/**
      - path: /pay-ws/**
      - path: /heartCheck.txt
      - path: /index.html
      - path: /favicon.ico
      - path: /sysUser/generateCaptcha
      - path: /sysUser/loginByPassword
  rsa:
    primaryKey: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAIPT0VbUrdYMIX//tgHgaMh9PUtqG6R/lNOvIl9LR6Mbc5J03qjvLlu2IifHFbFonm6XguZG4LZ4H3hRkX9fC4qSaQR1vZBOvS1aNLRyvMZudISJygiag1qJOQMEwrb8JUZkP7NMpBNjYpmF344+25Il3axRnd1oVR4Hhp4tqEe1AgMBAAECgYBYv0i3BAbjitcirKuDJ+hi0K1rD8v8OkefGtAxByT7EYgEmNktMZgr9bmYvdZE0QGXwjhFfoHZVZUaEw+4h+vkJrXxv2FQHqTSL8fDeL4jggNO3YYpLFoq9bvwWeqDJ3vvVkJEbNycfoE6iXv91mUM3hb7ie1NlvWYOJtiAxf0AQJBAOzyLcea/8Au8nVnJrVstpVaItkib7pT/9w2BDAe821JTXsmUCGw47LpYHZos6G8pR9Hz8VRaj99z8Z5xa2fe2ECQQCObaUe0n67ddr3OExVF9LyFVEdGzvuOwJjQi6/URvhrQDV31kld2z9lqV6p2l6JpDpmQIwPsJTS7qbLLhjGqDVAkEAz+Gh3I/Wdiw6OFqpkV6xydLs5AfccmMkBXW2sulUtLstKTBx+T0SaHNsWDZ/8xRo4krEtN87Ej01P3KyxiM3wQJAaJirF5ycR40AtmeY3zD00KXJAOgcNhMN6NkUvZmSMUS9BVPWAwbWetEkS5QgiP1DlNmyWr3sNgG6U/UeoGFQ1QJAZief8zE0C5jCmWf7VwfAJCSd+r+BVcSCpUxskc3gnhfG6j+ImAirhXIY+ld8rArmGl4UPkQfapBphUJslWLpLg==
    publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCD09FW1K3WDCF//7YB4GjIfT1Lahukf5TTryJfS0ejG3OSdN6o7y5btiInxxWxaJ5ul4LmRuC2eB94UZF/XwuKkmkEdb2QTr0tWjS0crzGbnSEicoImoNaiTkDBMK2/CVGZD+zTKQTY2KZhd+OPtuSJd2sUZ3daFUeB4aeLahHtQIDAQAB

leaf:
  name: com.sankuai.leaf.opensource.snowflake
  segment:
    enable: false
  snowflake:
    enable: true
    address: ${zk_addr}
