nacos:
  config:
    server-addr: ${nocos_server}
    username: ${nacos_username}
    password: ${nacos_password}
    auto-refresh: true
    config-retry-time: 3000
    namespace: common
    group: DEFAULT_GROUP
    enable-remote-sync-config: false
    type: yaml
    data-ids: common-server,common-global-properties,common-mybatis-plus,common-datasource,common-redis,common-mail,common-rocketmq,common-xxl-job,common-jwt,common-ids
    ext-config:
      - namespace: spring-boot-quick
        dataId: property-source
        group: dev
        type: properties
        auto-refresh: true

      - dataId: config-properties
        type: properties
        auto-refresh: true

      - dataId: config-server
        type: yaml
        auto-refresh: true

customs: # 自定义的属性最好都写在custom前缀下，方便辨认
  authentication:
    reset-password: 123456
    white-login-name-list:
      - 1041765757@qq.com
      - 123@test.com
